// admin/ui/src/App.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Button from 'primevue/button'
import Toast from 'primevue/toast'
import ConfirmDialog from 'primevue/confirmdialog'
import { clearMe, getMe, type Me } from './api'
import { faceitBadgeStyle, faceitLevel } from './faceit'

const route = useRoute(); const router = useRouter()
const isLogin = computed(() => route.path === '/login')
const me = ref<Me | null>(null)
watch(() => route.path, async () => { if (!isLogin.value) me.value = await getMe() }, { immediate: true })
const links = computed(() => me.value?.isAdmin
  ? [{ to:'/', label:'Серверы' }, { to:'/players', label:'Игроки' }, { to:'/skinchanger', label:'Skinchanger' }]
  : [{ to:'/skinchanger', label:'Skinchanger' }])
const currentFaceitLevel = computed(() => me.value?.faceitElo ? faceitLevel(me.value.faceitElo) : 0)
async function logout(){ await fetch('/api/auth/logout',{method:'POST'}); clearMe(); await router.push('/login') }
</script>

<template>
  <Toast/><ConfirmDialog/>
  <RouterView v-if="isLogin"/>
  <div v-else class="app-shell">
    <header class="topbar">
      <div class="topbar-inner">
        <RouterLink to="/" class="wordmark"><span>V</span>VERONA</RouterLink>
        <nav><RouterLink v-for="link in links" :key="link.to" :to="link.to">{{link.label}}</RouterLink></nav>
        <div class="account" v-if="me">
          <div v-if="me.faceitElo" class="elo-badge"><img :src="`/faceit/lvl${currentFaceitLevel}.svg`" class="elo-level-img" :alt="`Level ${currentFaceitLevel}`" /><b>{{me.faceitElo}} ELO</b></div>
          <img v-if="me.avatarUrl" :src="me.avatarUrl" alt=""/><i v-else class="pi pi-user"/>
          <span>{{me.name}}</span>
          <Button icon="pi pi-sign-out" text rounded severity="secondary" aria-label="Выйти" @click="logout"/>
        </div>
      </div>
    </header>
    <main class="content"><RouterView/></main>
  </div>
</template>

// admin/ui/src/App.tsx
import { lazy, Suspense, useEffect, useState } from "react";
import {
  Navigate,
  NavLink,
  Route,
  Routes,
  useLocation,
  useNavigate,
} from "react-router-dom";
import {
  SignOut,
  UsersThree,
  GameController,
  PaintBrush,
} from "@phosphor-icons/react";
import { clearMe, getMe, type Me } from "./api";
import { faceitLevel } from "./faceit";
import { Button } from "./components/ui";
const DashboardView = lazy(() => import("./views/DashboardView"));
const PlayersView = lazy(() => import("./views/PlayersView"));
const SkinchangerView = lazy(() => import("./views/SkinchangerView"));
const LoginView = lazy(() => import("./views/LoginView"));

function Shell() {
  const [me, setMe] = useState<Me | null>(null),
    [loaded, setLoaded] = useState(false);
  const location = useLocation();
  const navigate = useNavigate();
  useEffect(() => {
    let active = true;
    void getMe().then((value) => {
      if (active) {
        setMe(value);
        setLoaded(true);
      }
    });
    return () => {
      active = false;
    };
  }, [location.pathname]);
  if (!loaded) return <div className="page-loader">VERONA CS2 // CONNECTING</div>;
  if (!me) return <Navigate to="/login" replace />;
  const links = me.isAdmin
    ? ([
        ["/", "Серверы", GameController],
        ["/players", "Игроки", UsersThree],
        ["/skinchanger", "Skinchanger", PaintBrush],
      ] as const)
    : ([["/skinchanger", "Skinchanger", PaintBrush]] as const);
  async function logout() {
    await fetch("/api/auth/logout", { method: "POST" });
    clearMe();
    navigate("/login");
  }
  return (
    <div className="app-shell">
      <header className="topbar">
        <div className="topbar-inner">
          <NavLink to="/" className="wordmark">
            <b>V</b>
            <span>VERONA CS2</span>
            <i />
          </NavLink>
          <nav>
            {links.map(([to, label, Icon]) => (
              <NavLink key={to} to={to} end={to === "/"}>
                <Icon size={16} />
                {label}
              </NavLink>
            ))}
          </nav>
          <div className="account">
            {me.faceitElo && (
              <span className="elo-badge">
                <img src={`/faceit/lvl${faceitLevel(me.faceitElo)}.svg`} />
                {me.faceitElo} ELO
              </span>
            )}
            {me.avatarUrl && (
              <img className="avatar" src={me.avatarUrl} alt="" />
            )}
            <span className="account-name">{me.name}</span>
            <Button
              variant="ghost"
              size="icon"
              onClick={logout}
              aria-label="Выйти"
            >
              <SignOut size={18} />
            </Button>
          </div>
        </div>
      </header>
      <div className="network-strip">
        <span>
          <i /> CONTROL PLANE
        </span>
        <b>LOCALHOST</b>
        <span>CS2 DEDICATED SERVER</span>
      </div>
      <main className="content">
        <Routes>
          <Route
            index
            element={
              me.isAdmin ? (
                <DashboardView />
              ) : (
                <Navigate to="/skinchanger" replace />
              )
            }
          />
          <Route
            path="players"
            element={
              me.isAdmin ? (
                <PlayersView />
              ) : (
                <Navigate to="/skinchanger" replace />
              )
            }
          />
          <Route path="skinchanger" element={<SkinchangerView />} />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </main>
    </div>
  );
}
export default function App() {
  const location = useLocation();
  return (
    <Suspense fallback={<div className="page-loader">VERONA CS2 // LOADING</div>}>
      {location.pathname === "/login" ? <LoginView /> : <Shell />}
    </Suspense>
  );
}
