// admin/ui/src/views/DashboardView.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { HubConnectionBuilder } from '@microsoft/signalr'
import Button from 'primevue/button'
import InputText from 'primevue/inputtext'
import Select from 'primevue/select'
import SelectButton from 'primevue/selectbutton'
import Slider from 'primevue/slider'
import Tag from 'primevue/tag'
import ToggleSwitch from 'primevue/toggleswitch'
import { useToast } from 'primevue/usetoast'
import { api } from '../api'

interface Status {
  container: { running: boolean; status: string; startedAt?: string }
  phase: 'stopped' | 'starting' | 'ready'; ready: boolean
  currentMap: string; online: number; lastHeartbeat: string
}
interface Launch {
  map: string; workshopMapId: string; gameType: number; gameMode: number; maxPlayers: number
  insecure: boolean; botsEnabled: boolean; botQuota: number; botDifficulty: number
  practice: boolean; infiniteAmmo: boolean; friendlyFire: boolean
}
interface Mode { label: string; hint: string; gameType: number; gameMode: number; maps: string[] }

const mapNames: Record<string, string> = {
  de_dust2: 'Dust II', de_mirage: 'Mirage', de_inferno: 'Inferno', de_nuke: 'Nuke',
  de_ancient: 'Ancient', de_anubis: 'Anubis', de_train: 'Train', de_overpass: 'Overpass', de_vertigo: 'Vertigo'
}
const activeDuty = ['de_dust2','de_mirage','de_inferno','de_nuke','de_ancient','de_anubis','de_train','de_overpass','de_vertigo']
// Wingman uses its own official pool: the big maps have no 2v2 layout.
const wingman = ['de_inferno','de_nuke','de_overpass','de_vertigo']
const modes: Mode[] = [
  { label: 'Casual', hint: 'Обычный: без ограничений, свободный вход', gameType: 0, gameMode: 0, maps: activeDuty },
  { label: 'Competitive', hint: 'Соревновательный: 5×5, MR24', gameType: 0, gameMode: 1, maps: activeDuty },
  { label: 'Wingman', hint: 'Напарники: 2×2, укороченные карты', gameType: 0, gameMode: 2, maps: wingman },
  { label: 'Deathmatch', hint: 'Deathmatch: мгновенное возрождение', gameType: 1, gameMode: 2, maps: activeDuty }
]
const mapSources = [ { label: 'Официальные', value: 'official' }, { label: 'Мастерская', value: 'workshop' } ]
const difficulties = [
  { label: 'Лёгкие', value: 0 }, { label: 'Средние', value: 1 },
  { label: 'Сложные', value: 2 }, { label: 'Эксперт', value: 3 }
]

const status = ref<Status | null>(null)
const busy = ref(false)
const mode = ref<Mode>(modes[0])
const map = ref('de_dust2')
const mapSource = ref<'official' | 'workshop'>('official')
const workshopId = ref('')
const maxPlayers = ref(10)
const vac = ref(true)
const friendlyFire = ref(false)
const botsEnabled = ref(true)
const botQuota = ref(5)
const botDifficulty = ref(1)
const practice = ref(false)
const infiniteAmmo = ref(false)
const toast = useToast()

const phaseLabel = computed(() => status.value?.phase === 'ready' ? 'Сервер готов' : status.value?.phase === 'starting' ? 'Сервер запускается' : 'Сервер остановлен')
const phaseSeverity = computed(() => status.value?.phase === 'ready' ? 'success' : status.value?.phase === 'starting' ? 'warn' : 'danger')
const displayMap = computed(() => status.value?.ready && status.value.currentMap !== 'unknown' ? status.value.currentMap : map.value)
const displayMapName = computed(() => mapNames[displayMap.value] ?? displayMap.value)
async function load() {
  status.value = await api<Status>('/api/server/status')
}
async function copyAddress() {
  await navigator.clipboard.writeText('localhost:27015')
  toast.add({ severity: 'success', summary: 'Адрес скопирован', detail: 'localhost:27015', life: 1800 })
}
async function loadLaunch() {
  const launch = await api<Launch>('/api/server/launch')
  mode.value = modes.find(m => m.gameType === launch.gameType && m.gameMode === launch.gameMode) ?? modes[0]
  map.value = mode.value.maps.includes(launch.map) ? launch.map : mode.value.maps[0]
  workshopId.value = launch.workshopMapId
  mapSource.value = launch.workshopMapId ? 'workshop' : 'official'
  maxPlayers.value = launch.maxPlayers
  vac.value = !launch.insecure
  botsEnabled.value = launch.botsEnabled
  botQuota.value = launch.botQuota
  botDifficulty.value = launch.botDifficulty
  practice.value = launch.practice
  infiniteAmmo.value = launch.infiniteAmmo
  friendlyFire.value = launch.friendlyFire
}
watch(mode, m => { if (!m.maps.includes(map.value)) map.value = m.maps[0] })
// Cheats-based options cannot work while VAC is active: drop it automatically.
watch([practice, infiniteAmmo], ([p, ammo]) => { if (p || ammo) vac.value = false })

async function action(name: 'start'|'stop'|'restart') {
  if (name === 'start' && mapSource.value === 'workshop' && !/^\d{1,20}$/.test(workshopId.value.trim())) {
    toast.add({ severity: 'warn', summary: 'Мастерская', detail: 'Укажите числовой ID карты из Steam Workshop', life: 4000 })
    return
  }
  busy.value = true
  try {
    const body = name === 'start'
      ? JSON.stringify({
          map: mapSource.value === 'official' ? map.value : null,
          workshopMapId: mapSource.value === 'workshop' ? workshopId.value.trim() : '',
          gameType: mode.value.gameType, gameMode: mode.value.gameMode,
          maxPlayers: maxPlayers.value, insecure: !vac.value,
          botsEnabled: botsEnabled.value, botQuota: botQuota.value, botDifficulty: botDifficulty.value,
          practice: practice.value, infiniteAmmo: infiniteAmmo.value, friendlyFire: friendlyFire.value
        })
      : undefined
    await api(`/api/server/${name}`, { method: 'POST', body })
    await new Promise(r => setTimeout(r, 300)); await load()
  }
  catch (e) { toast.add({ severity: 'error', summary: 'Ошибка', detail: String(e), life: 4000 }) }
  finally { busy.value = false }
}
let timer = 0
const hub = new HubConnectionBuilder().withUrl('/hub').withAutomaticReconnect().build()
onMounted(async () => { await load(); await loadLaunch(); timer = window.setInterval(load, 2000); hub.on('serverChanged', load); await hub.start().catch(() => {}) })
onUnmounted(() => { clearInterval(timer); void hub.stop() })
</script>

<template>
  <header class="page-header"><div><p class="eyebrow">VERONA NETWORK</p><h1>Серверы</h1></div><span class="muted">1 сервер · {{ status?.online ?? 0 }} игроков онлайн</span></header>

  <section class="server-list">
    <article class="server-card" :style="{ '--map-image': `url(/maps/${displayMap}.png)` }">
      <div class="server-shade" />
      <div class="server-card-main">
        <div class="server-card-title"><span class="server-index">01</span><div><h2>Verona #1</h2><p>{{ mode.label }} · {{ displayMapName }}</p></div></div>
        <Tag :severity="phaseSeverity" :value="phaseLabel" :icon="status?.phase === 'starting' ? 'pi pi-spin pi-spinner' : undefined" />
      </div>
      <div class="server-meta">
        <span><i class="pi pi-users" /> {{ status?.online ?? 0 }}/{{ maxPlayers }}</span>
        <span><i class="pi pi-map" /> {{ displayMapName }}</span>
        <button class="copy-address" type="button" title="Скопировать адрес" @click="copyAddress"><i class="pi pi-copy" /> localhost:27015</button>
      </div>
      <div class="server-card-actions" v-if="status?.container.running">
        <Button label="Перезапустить" icon="pi pi-refresh" severity="secondary" size="small" :loading="busy" @click="action('restart')" />
        <Button label="Остановить" icon="pi pi-stop" severity="danger" size="small" outlined :loading="busy" @click="action('stop')" />
      </div>
    </article>
  </section>

  <section class="panel launch-panel" v-if="status && !status.container.running">
    <div class="launch-head">
      <div><h2>Запуск сервера</h2><p>Режим, карта и настройки применяются при старте.</p></div>
      <Button label="Запустить сервер" icon="pi pi-play" size="large" :loading="busy" @click="action('start')" />
    </div>

    <div class="launch-block">
      <label>Режим игры</label>
      <SelectButton v-model="mode" :options="modes" optionLabel="label" :allowEmpty="false" />
      <p class="muted">{{ mode.hint }}</p>
    </div>

    <div class="launch-block">
      <div class="launch-row">
        <label>Карта</label>
        <SelectButton v-model="mapSource" :options="mapSources" optionLabel="label" optionValue="value" :allowEmpty="false" />
      </div>
      <div v-if="mapSource === 'official'" class="map-grid">
        <button v-for="m in mode.maps" :key="m" type="button" class="map-card" :class="{ selected: map === m }" @click="map = m">
          <img :src="`/maps/${m}.png`" :alt="mapNames[m] ?? m" loading="lazy" />
          <span>{{ mapNames[m] ?? m }}</span>
          <i v-if="map === m" class="pi pi-check-circle" />
        </button>
      </div>
      <div v-else class="workshop-row">
        <InputText v-model="workshopId" placeholder="ID карты из мастерской, например 3070284539" />
        <p class="muted">Сервер сам скачает карту из Steam Workshop при запуске. ID — число из ссылки steamcommunity.com/sharedfiles/filedetails/?id=…</p>
      </div>
    </div>

    <div class="launch-block">
      <label>Игроки и боты</label>
      <div class="settings-grid">
        <div class="setting"><span>Макс. игроков: <b>{{ maxPlayers }}</b></span><Slider v-model="maxPlayers" :min="2" :max="32" /></div>
        <div class="setting toggle"><span>Боты<small>bot_quota_mode fill — добивают до квоты</small></span><ToggleSwitch v-model="botsEnabled" /></div>
        <div class="setting" :class="{ disabled: !botsEnabled }"><span>Количество ботов: <b>{{ botQuota }}</b></span><Slider v-model="botQuota" :min="0" :max="12" :disabled="!botsEnabled" /></div>
        <div class="setting" :class="{ disabled: !botsEnabled }"><span>Сложность ботов</span><Select v-model="botDifficulty" :options="difficulties" optionLabel="label" optionValue="value" :disabled="!botsEnabled" /></div>
      </div>
    </div>

    <div class="launch-block">
      <label>Сервер</label>
      <div class="settings-grid">
        <div class="setting toggle"><span>VAC<small>защита от читов; несовместима с режимами ниже</small></span><ToggleSwitch v-model="vac" /></div>
        <div class="setting toggle"><span>Огонь по своим<small>mp_friendlyfire</small></span><ToggleSwitch v-model="friendlyFire" /></div>
        <div class="setting toggle"><span>Режим тренировки<small>sv_cheats, 60 000$, покупка везде, раунды по 60 мин, respawn</small></span><ToggleSwitch v-model="practice" /></div>
        <div class="setting toggle"><span>Бесконечные патроны<small>sv_infinite_ammo 1, включает sv_cheats</small></span><ToggleSwitch v-model="infiniteAmmo" /></div>
      </div>
    </div>
  </section>

</template>

// admin/ui/src/views/DashboardView.tsx
import { useEffect, useMemo, useState } from "react";
import { HubConnectionBuilder } from "@microsoft/signalr";
import {
  Copy,
  GameController,
  MapPin,
  Play,
  Power,
  SpinnerGap,
  UsersThree,
} from "@phosphor-icons/react";
import { toast } from "sonner";
import { api } from "../api";
import { Badge, Button, Input, Select, Slider, Switch } from "../components/ui";
import { Tabs, TabsList, TabsTrigger } from "../components/ui/tabs";

interface Status {
  container: { running: boolean; status: string };
  phase: "stopped" | "starting" | "ready";
  ready: boolean;
  currentMap: string;
  online: number;
  lastHeartbeat: string;
}
interface Launch {
  map: string;
  workshopMapId: string;
  gameType: number;
  gameMode: number;
  maxPlayers: number;
  insecure: boolean;
  botsEnabled: boolean;
  botQuota: number;
  botDifficulty: number;
  practice: boolean;
  infiniteAmmo: boolean;
  friendlyFire: boolean;
}
interface Mode {
  label: string;
  hint: string;
  gameType: number;
  gameMode: number;
  maps: string[];
}
const names: Record<string, string> = {
  de_dust2: "Dust II",
  de_mirage: "Mirage",
  de_inferno: "Inferno",
  de_nuke: "Nuke",
  de_ancient: "Ancient",
  de_anubis: "Anubis",
  de_train: "Train",
  de_overpass: "Overpass",
  de_vertigo: "Vertigo",
};
const pool = Object.keys(names),
  wingman = ["de_inferno", "de_nuke", "de_overpass", "de_vertigo"];
const modes: Mode[] = [
  {
    label: "Casual",
    hint: "Свободный вход без рейтинговых ограничений",
    gameType: 0,
    gameMode: 0,
    maps: pool,
  },
  {
    label: "Competitive",
    hint: "Классический соревновательный режим 5×5",
    gameType: 0,
    gameMode: 1,
    maps: pool,
  },
  {
    label: "Wingman",
    hint: "Компактный соревновательный режим 2×2",
    gameType: 0,
    gameMode: 2,
    maps: wingman,
  },
  {
    label: "Deathmatch",
    hint: "Мгновенное возрождение и непрерывный бой",
    gameType: 1,
    gameMode: 2,
    maps: pool,
  },
];

export default function DashboardView() {
  const [status, setStatus] = useState<Status | null>(null),
    [busy, setBusy] = useState(false),
    [mode, setMode] = useState(modes[0]),
    [map, setMap] = useState("de_dust2"),
    [source, setSource] = useState<"official" | "workshop">("official"),
    [workshop, setWorkshop] = useState(""),
    [maxPlayers, setMaxPlayers] = useState(10),
    [vac, setVac] = useState(true),
    [bots, setBots] = useState(true),
    [botQuota, setBotQuota] = useState(5),
    [difficulty, setDifficulty] = useState(1),
    [practice, setPractice] = useState(false),
    [ammo, setAmmo] = useState(false),
    [friendly, setFriendly] = useState(false);
  const load = () => api<Status>("/api/server/status").then(setStatus);
  useEffect(() => {
    let timer = 0,
      active = true;
    const hub = new HubConnectionBuilder()
      .withUrl("/hub")
      .withAutomaticReconnect()
      .build();
    void Promise.all([
      load(),
      api<Launch>("/api/server/launch").then((x) => {
        if (!active) return;
        const m =
          modes.find(
            (v) => v.gameType === x.gameType && v.gameMode === x.gameMode,
          ) ?? modes[0];
        setMode(m);
        setMap(m.maps.includes(x.map) ? x.map : m.maps[0]);
        setWorkshop(x.workshopMapId);
        setSource(x.workshopMapId ? "workshop" : "official");
        setMaxPlayers(x.maxPlayers);
        setVac(!x.insecure);
        setBots(x.botsEnabled);
        setBotQuota(x.botQuota);
        setDifficulty(x.botDifficulty);
        setPractice(x.practice);
        setAmmo(x.infiniteAmmo);
        setFriendly(x.friendlyFire);
      }),
    ]).then(() => {
      if (!active) return;
      timer = window.setInterval(load, 2000);
      hub.on("serverChanged", load);
      void hub.start().catch(() => {});
    });
    return () => {
      active = false;
      clearInterval(timer);
      void hub.stop();
    };
  }, []);
  useEffect(() => {
    if (!mode.maps.includes(map)) setMap(mode.maps[0]);
  }, [mode, map]);
  useEffect(() => {
    if (practice || ammo) setVac(false);
  }, [practice, ammo]);
  const display =
      status?.ready && status.currentMap !== "unknown"
        ? status.currentMap
        : map,
    phase =
      status?.phase === "ready"
        ? "Сервер готов"
        : status?.phase === "starting"
          ? "Запускается"
          : "Остановлен";
  async function action(name: "start" | "stop" | "restart") {
    if (
      name === "start" &&
      source === "workshop" &&
      !/^\d{1,20}$/.test(workshop.trim())
    ) {
      toast.warning("Укажите числовой Workshop ID");
      return;
    }
    setBusy(true);
    try {
      await api(`/api/server/${name}`, {
        method: "POST",
        body:
          name === "start"
            ? JSON.stringify({
                map: source === "official" ? map : null,
                workshopMapId: source === "workshop" ? workshop.trim() : "",
                gameType: mode.gameType,
                gameMode: mode.gameMode,
                maxPlayers,
                insecure: !vac,
                botsEnabled: bots,
                botQuota,
                botDifficulty: difficulty,
                practice,
                infiniteAmmo: ammo,
                friendlyFire: friendly,
              })
            : undefined,
      });
      await load();
      toast.success("Команда отправлена");
    } catch (e) {
      toast.error(String(e));
    } finally {
      setBusy(false);
    }
  }
  const settings = useMemo(
    () =>
      [
        ["VAC", "Защита от читов", vac, setVac],
        ["Огонь по своим", "mp_friendlyfire", friendly, setFriendly],
        ["Practice", "Расширенный тренировочный режим", practice, setPractice],
        ["Бесконечные патроны", "sv_infinite_ammo 1", ammo, setAmmo],
      ] as const,
    [vac, friendly, practice, ammo],
  );
  return (
    <>
      <header className="page-header">
        <div>
          <p className="kicker">SERVER NETWORK</p>
          <h1>Серверы</h1>
        </div>
        <div className="headline-stat">
          <i />
          <b>{status?.online ?? 0}</b> игроков онлайн
        </div>
      </header>
      <section
        className="server-hero"
        style={{ "--map": `url(/maps/${display}.png)` } as React.CSSProperties}
      >
        <div className="server-hero-shade" />
        <div className="server-top">
          <span className="server-number">01</span>
          <div>
            <h2>VERONA #1</h2>
            <p>
              {mode.label} · {names[display] ?? display}
            </p>
          </div>
          <Badge
            tone={
              status?.phase === "ready"
                ? "success"
                : status?.phase === "starting"
                  ? "warning"
                  : "danger"
            }
          >
            {status?.phase === "starting" && <SpinnerGap className="spin" />}
            {phase}
          </Badge>
        </div>
        <div className="server-bottom">
          <span>
            <UsersThree /> {status?.online ?? 0}/{maxPlayers}
          </span>
          <span>
            <MapPin /> {names[display] ?? display}
          </span>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => {
              void navigator.clipboard.writeText("localhost:27015");
              toast.success("Адрес скопирован");
            }}
          >
            <Copy /> localhost:27015
          </Button>
          {status?.container.running ? (
            <div className="server-actions">
              <Button
                variant="secondary"
                disabled={busy}
                onClick={() => action("restart")}
              >
                Перезапустить
              </Button>
              <Button
                variant="danger"
                disabled={busy}
                onClick={() => action("stop")}
              >
                <Power /> Остановить
              </Button>
            </div>
          ) : null}
        </div>
      </section>
      {!status?.container.running && (
        <section className="launch-console">
          <div className="section-head">
            <div>
              <p className="kicker">LAUNCH CONFIGURATION</p>
              <h2>Новый запуск</h2>
              <p>Параметры применятся при старте контейнера.</p>
            </div>
            <Button disabled={busy} onClick={() => action("start")}>
              <Play weight="fill" /> Запустить сервер
            </Button>
          </div>
          <div className="config-block">
            <label>Режим игры</label>
            <Tabs
              value={mode.label}
              onValueChange={(value) =>
                setMode(modes.find((item) => item.label === value) ?? modes[0])
              }
            >
              <TabsList>
                {modes.map((item) => (
                  <TabsTrigger value={item.label} key={item.label}>
                    {item.label}
                  </TabsTrigger>
                ))}
              </TabsList>
            </Tabs>
            <small>{mode.hint}</small>
          </div>
          <div className="config-block">
            <div className="config-title">
              <label>Карта</label>
              <Tabs
                value={source}
                onValueChange={(value) =>
                  setSource(value as "official" | "workshop")
                }
              >
                <TabsList>
                  <TabsTrigger value="official">Официальные</TabsTrigger>
                  <TabsTrigger value="workshop">Workshop</TabsTrigger>
                </TabsList>
              </Tabs>
            </div>
            {source === "official" ? (
              <div className="map-grid">
                {mode.maps.map((m) => (
                  <button
                    key={m}
                    className={map === m ? "selected" : ""}
                    onClick={() => setMap(m)}
                  >
                    <img src={`/maps/${m}.png`} alt="" />
                    <span>{names[m]}</span>
                  </button>
                ))}
              </div>
            ) : (
              <Input
                value={workshop}
                onChange={(e) => setWorkshop(e.target.value)}
                placeholder="Workshop ID, например 3070284539"
              />
            )}
          </div>
          <div className="config-block">
            <label>Игроки и боты</label>
            <div className="settings-grid">
              <Setting
                title={`Максимум игроков: ${maxPlayers}`}
                hint="2–32 слота"
              >
                <Slider
                  value={[maxPlayers]}
                  onValueChange={(v) => setMaxPlayers(v[0])}
                  min={2}
                  max={32}
                />
              </Setting>
              <Setting title="Боты" hint="Заполняют сервер до квоты">
                <Switch checked={bots} onCheckedChange={setBots} />
              </Setting>
              <Setting title={`Количество ботов: ${botQuota}`} hint="bot_quota">
                <Slider
                  value={[botQuota]}
                  onValueChange={(v) => setBotQuota(v[0])}
                  min={0}
                  max={12}
                  disabled={!bots}
                />
              </Setting>
              <Setting title="Сложность" hint="Уровень AI">
                <Select
                  value={difficulty}
                  onChange={(e) => setDifficulty(+e.target.value)}
                  disabled={!bots}
                >
                  <option value={0}>Лёгкие</option>
                  <option value={1}>Средние</option>
                  <option value={2}>Сложные</option>
                  <option value={3}>Эксперт</option>
                </Select>
              </Setting>
            </div>
          </div>
          <div className="config-block">
            <label>Правила сервера</label>
            <div className="settings-grid">
              {settings.map(([t, h, v, s]) => (
                <Setting key={t} title={t} hint={h}>
                  <Switch checked={v} onCheckedChange={s} />
                </Setting>
              ))}
            </div>
          </div>
        </section>
      )}
    </>
  );
}
function Setting({
  title,
  hint,
  children,
}: {
  title: string;
  hint: string;
  children: React.ReactNode;
}) {
  return (
    <div className="setting">
      <div>
        <b>{title}</b>
        <small>{hint}</small>
      </div>
      {children}
    </div>
  );
}
