// admin/ui/src/views/SkinchangerView.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import Button from 'primevue/button'
import Dialog from 'primevue/dialog'
import InputNumber from 'primevue/inputnumber'
import InputText from 'primevue/inputtext'
import Select from 'primevue/select'
import Slider from 'primevue/slider'
import { useToast } from 'primevue/usetoast'
import { useConfirm } from 'primevue/useconfirm'
import { api, getMe, type Me, type Skin } from '../api'
import { faceitBadgeStyle, faceitLevel } from '../faceit'

interface CatalogWeapon { weapon: string; name: string; category: string; image: string }
interface CatalogSkin { name: string; weapon: string; weaponName: string; category: string; paint: number; color: string; image: string; minWear: number; maxWear: number }
interface KnownPlayer { steamId: string; name: string; lastSeenAt: string; avatarUrl?: string | null; profileUrl?: string | null; faceitElo?: number | null; faceitNickname?: string | null }
interface SkinCollection { id:number; name:string; active:boolean; count:number }

const categories = [
  { id: 'sfui_invpanel_filter_melee', label: 'Ножи' },
  { id: 'all', label: 'Всё' },
  { id: 'csgo_inventory_weapon_category_pistols', label: 'Пистолеты' },
  { id: 'csgo_inventory_weapon_category_rifles', label: 'Винтовки' },
  { id: 'csgo_inventory_weapon_category_smgs', label: 'SMG' },
  { id: 'csgo_inventory_weapon_category_heavy', label: 'Тяжёлое' },
  { id: 'loadoutslot_equipment', label: 'Zeus' }
]

const me = ref<Me | null>(null)
const weapons = ref<CatalogWeapon[]>([])
const skinsByWeapon = ref<Map<string, CatalogSkin[]>>(new Map())
const mySkins = ref<Record<string, Skin>>({})
const category = ref('all')
const search = ref('')
const loading = ref(true)
const toast = useToast()
const confirm = useConfirm()
const route = useRoute()

// Admins can retarget the editor at any account the server has ever seen.
const players = ref<KnownPlayer[]>([])
const target = ref<KnownPlayer | null>(null)
const editingSelf = computed(() => !me.value?.isAdmin || !target.value || target.value.steamId === me.value?.steamId)
// This is UX only. Backend is the security boundary: /api/me derives SteamID from
// the session, while an arbitrary /api/players target requires an admin session.
const basePath = computed(() => editingSelf.value ? '/api/me/skins' : `/api/players/${target.value!.steamId}/skins`)
const profile = computed(() => editingSelf.value
  ? me.value && ({ steamId: me.value.steamId, name: me.value.name, avatarUrl: me.value.avatarUrl,
      profileUrl: `https://steamcommunity.com/profiles/${me.value.steamId}`, faceitElo: me.value.faceitElo, faceitNickname: me.value.faceitNickname })
  : target.value)

const visibleWeapons = computed(() => {
  const query = search.value.trim().toLowerCase()
  return weapons.value.filter(w =>
    (category.value === 'all' || w.category === category.value) &&
    (!query || w.name.toLowerCase().includes(query) || (currentSkin(w.weapon)?.name ?? '').toLowerCase().includes(query)))
})
function currentSkin(weapon: string): CatalogSkin | null {
  const applied = mySkins.value[weapon]
  if (!applied) return null
  return skinsByWeapon.value.get(weapon)?.find(s => s.paint === applied.paintKit) ?? null
}

async function loadSkins() {
  if (me.value?.isAdmin && !target.value) { mySkins.value = {}; return }
  const list = await api<Skin[]>(basePath.value)
  mySkins.value = Object.fromEntries(list.map(s => [s.weapon, s]))
}
async function retarget() { await loadSkins() }

// Skin picker dialog state.
const dialog = ref(false)
const dialogWeapon = ref<CatalogWeapon | null>(null)
const dialogSearch = ref('')
const picked = ref<CatalogSkin | null>(null)
const wear = ref(0.01)
const seed = ref(0)
const saving = ref(false)
const collections = ref<SkinCollection[]>([])
const collectionDialog = ref(false)
const collectionName = ref('')
const dialogSkins = computed(() => {
  const all = dialogWeapon.value ? (skinsByWeapon.value.get(dialogWeapon.value.weapon) ?? []) : []
  const query = dialogSearch.value.trim().toLowerCase()
  return query ? all.filter(s => s.name.toLowerCase().includes(query)) : all
})
function openWeapon(weapon: CatalogWeapon) {
  if (editingSelf.value && collections.value.length === 0) {
    toast.add({ severity: 'warn', summary: 'Внимание', detail: 'Необходимо создать коллекцию перед выбором скинов', life: 4000 })
    return
  }
  dialogWeapon.value = weapon
  dialogSearch.value = ''
  picked.value = currentSkin(weapon.weapon)
  const applied = mySkins.value[weapon.weapon]
  wear.value = applied?.wear ?? 0.01
  seed.value = applied?.seed ?? 0
  dialog.value = true
}
function pick(skin: CatalogSkin) {
  picked.value = skin
  wear.value = Math.min(Math.max(wear.value, skin.minWear), skin.maxWear)
}
async function save() {
  if (!dialogWeapon.value || !picked.value) return
  saving.value = true
  try {
    await api(`${basePath.value}/${dialogWeapon.value.weapon}`, {
      method: 'PUT',
      body: JSON.stringify({ weapon: dialogWeapon.value.weapon, paintKit: picked.value.paint, wear: wear.value, seed: seed.value })
    })
    await loadSkins()
    dialog.value = false
    toast.add({ severity: 'success', summary: 'Скин сохранён', detail: `${picked.value.name} применится при следующей выдаче оружия`, life: 3000 })
  } catch (e) { toast.add({ severity: 'error', summary: 'Ошибка', detail: String(e), life: 4000 }) }
  finally { saving.value = false }
}
async function resetSkin() {
  if (!dialogWeapon.value || !mySkins.value[dialogWeapon.value.weapon]) { dialog.value = false; return }
  saving.value = true
  try {
    await api(`${basePath.value}/${dialogWeapon.value.weapon}`, { method: 'DELETE' })
    await loadSkins()
    dialog.value = false
    toast.add({ severity: 'success', summary: 'Скин сброшен', life: 2500 })
  } catch (e) { toast.add({ severity: 'error', summary: 'Ошибка', detail: String(e), life: 4000 }) }
  finally { saving.value = false }
}
async function loadCollections() {
  if (editingSelf.value) {
    collections.value = await api<SkinCollection[]>('/api/me/collections')
    if (collections.value.length === 0) {
      await api('/api/me/collections', {
        method: 'POST',
        body: JSON.stringify({ name: 'По умолчанию' })
      })
      collections.value = await api<SkinCollection[]>('/api/me/collections')
      await loadSkins()
    }
  }
}
async function createCollection(){ const name=collectionName.value.trim();if(!name)return;await api('/api/me/collections',{method:'POST',body:JSON.stringify({name})});collectionName.value='';collectionDialog.value=false;await loadCollections() }
async function activateCollection(item:SkinCollection){ if(item.active)return;await api(`/api/me/collections/${item.id}/activate`,{method:'POST'});await Promise.all([loadCollections(),loadSkins()]) }
async function confirmDeleteCollection(item: SkinCollection) {
  confirm.require({
    message: `Вы уверены, что хотите удалить коллекцию "${item.name}"?`,
    header: 'Подтверждение удаления',
    icon: 'pi pi-exclamation-triangle',
    rejectProps: { label: 'Отмена', severity: 'secondary', text: true },
    acceptProps: { label: 'Удалить', severity: 'danger' },
    accept: async () => {
      try {
        await api(`/api/me/collections/${item.id}`, { method: 'DELETE' })
        toast.add({ severity: 'success', summary: 'Коллекция удалена', life: 2500 })
        await Promise.all([loadCollections(), loadSkins()])
      } catch (e) {
        toast.add({ severity: 'error', summary: 'Ошибка', detail: String(e), life: 4000 })
      }
    }
  })
}
const importDialog = ref(false)
const importCode = ref('')
async function shareCollection(item: SkinCollection) {
  try {
    const skins = await api<Skin[]>(`/api/me/collections/${item.id}/skins`)
    const data = {
      name: item.name,
      skins: skins.map(s => ({ weapon: s.weapon, paintKit: s.paintKit, wear: s.wear, seed: s.seed }))
    }
    const code = btoa(unescape(encodeURIComponent(JSON.stringify(data))))
    await navigator.clipboard.writeText(code)
    toast.add({ severity: 'success', summary: 'Код скопирован', detail: 'Код коллекции скопирован в буфер обмена', life: 3000 })
  } catch (e) {
    toast.add({ severity: 'error', summary: 'Ошибка', detail: String(e), life: 4000 })
  }
}
async function importCollection() {
  const code = importCode.value.trim()
  if (!code) return
  try {
    const raw = decodeURIComponent(escape(atob(code)))
    const data = JSON.parse(raw)
    if (!data.name || !Array.isArray(data.skins)) {
      throw new Error('Неверный формат кода коллекции')
    }
    await api('/api/me/collections', {
      method: 'POST',
      body: JSON.stringify({ name: data.name, skins: data.skins })
    })
    importCode.value = ''
    importDialog.value = false
    toast.add({ severity: 'success', summary: 'Коллекция импортирована', life: 3000 })
    await loadCollections()
  } catch (e) {
    toast.add({ severity: 'error', summary: 'Ошибка импорта', detail: 'Не удалось распознать код коллекции. Убедитесь, что скопировали его полностью.', life: 4000 })
  }
}

onMounted(async () => {
  me.value = await getMe()
  // Catalog metadata is public/static for cache-friendly delivery. Save endpoints
  // still validate submitted values because browser data is never trusted.
  const catalog = await (await fetch('/skins-catalog.json')).json() as { weapons: CatalogWeapon[]; skins: CatalogSkin[] }
  weapons.value = catalog.weapons
  const grouped = new Map<string, CatalogSkin[]>()
  for (const skin of catalog.skins) {
    const list = grouped.get(skin.weapon) ?? []
    list.push(skin); grouped.set(skin.weapon, list)
  }
  skinsByWeapon.value = grouped
  if (me.value?.isAdmin) {
    players.value = await api<KnownPlayer[]>('/api/players/known')
    const requestedSteamId = typeof route.query.steamId === 'string' ? route.query.steamId : null
    target.value = players.value.find(p => p.steamId === requestedSteamId)
      ?? players.value.find(p => p.steamId === me.value?.steamId)
      ?? (me.value.steamId ? { steamId: me.value.steamId, name: me.value.name, lastSeenAt: '' } : players.value[0] ?? null)
  }
  await loadSkins()
  await loadCollections()
  loading.value = false
})
</script>

<template>
  <header class="page-header">
    <div><p class="eyebrow">SKINCHANGER</p><h1>Скины оружия</h1></div>
    <div class="target-picker" v-if="me?.isAdmin">
      <label>Игрок</label>
      <Select v-model="target" :options="players" optionLabel="name" filter placeholder="Выберите игрока" @change="retarget">
        <template #option="{ option }"><span>{{ option.name }}</span><span class="muted steamid">{{ option.steamId }}</span></template>
      </Select>
    </div>
  </header>
  <section v-if="profile" class="profile-card">
    <img v-if="profile.avatarUrl" :src="profile.avatarUrl" alt="" />
    <div class="profile-main"><h2>{{ profile.name }}</h2><span>{{ profile.steamId }}</span></div>
    <a class="profile-steam" :href="profile.profileUrl || `https://steamcommunity.com/profiles/${profile.steamId}`" target="_blank"><i class="pi pi-external-link" /> Steam</a>
    <a v-if="profile.faceitElo" :class="['elo-badge', 'profile-elo', profile.faceitNickname ? 'clickable' : '']" :href="profile.faceitNickname ? `https://www.faceit.com/ru/players/${profile.faceitNickname}` : undefined" target="_blank">
      <img :src="`/faceit/lvl${faceitLevel(profile.faceitElo)}.svg`" class="elo-level-img" :alt="`Level ${faceitLevel(profile.faceitElo)}`" />
      <b>{{ profile.faceitElo }} ELO</b>
    </a>
  </section>

  <section class="skinchanger-layout">
  <aside v-if="editingSelf" class="collections-panel">
    <p class="eyebrow">КОЛЛЕКЦИИ · {{ collections.length }}</p>
    <div v-for="item in collections" :key="item.id" class="collection-item" :class="{ active:item.active }" role="button" tabindex="0" @click="activateCollection(item)" @keydown.enter="activateCollection(item)">
      <span>{{item.name}}</span>
      <small>{{item.count}} скинов</small>
      <div class="collection-actions">
        <button type="button" class="collection-action share" title="Поделиться" @click.stop="shareCollection(item)">
          <i class="pi pi-share-alt" />
        </button>
        <button type="button" class="collection-action delete" title="Удалить коллекцию" @click.stop="confirmDeleteCollection(item)">
          <i class="pi pi-trash" />
        </button>
      </div>
    </div>
    <div class="collections-buttons">
      <button type="button" class="collection-btn" @click="collectionDialog=true"><i class="pi pi-plus"/> Создать</button>
      <button type="button" class="collection-btn" @click="importDialog=true"><i class="pi pi-download"/> Импорт</button>
    </div>
  </aside>
  <div class="skinchanger-main">
  <section class="panel skin-toolbar">
    <div class="cat-tabs">
      <button v-for="c in categories" :key="c.id" type="button" class="cat-tab" :class="{ active: category === c.id }" @click="category = c.id">{{ c.label }}</button>
    </div>
    <InputText v-model="search" placeholder="Поиск..." class="skin-search" />
  </section>

  <p v-if="me?.isAdmin && !target" class="muted">Выберите игрока, чтобы редактировать его скины.</p>
  <section v-else class="weapon-grid">
    <button v-for="w in visibleWeapons" :key="w.weapon" type="button" class="weapon-card" :style="{ '--rarity': currentSkin(w.weapon)?.color ?? '#30343d' }" @click="openWeapon(w)">
      <span v-if="currentSkin(w.weapon)" class="rarity-dot" :style="{ background: currentSkin(w.weapon)!.color }" />
      <img :src="currentSkin(w.weapon)?.image || w.image" :alt="w.name" loading="lazy" :class="{ vanilla: !currentSkin(w.weapon) }" />
      <span class="weapon-title">{{ w.name }}</span>
      <span class="skin-title" :class="{ muted: !currentSkin(w.weapon) }">{{ currentSkin(w.weapon)?.name.split('| ')[1] ?? 'Добавить скин' }}</span>
    </button>
  </section>
  </div>
  </section>

  <Dialog v-model:visible="collectionDialog" modal header="Новая коллекция" :style="{width:'28rem'}">
    <div class="field"><label>Название</label><InputText v-model="collectionName" maxlength="48" placeholder="Например, Competitive" autofocus /></div>
    <template #footer><Button label="Отмена" text @click="collectionDialog=false"/><Button label="Создать" icon="pi pi-plus" @click="createCollection"/></template>
  </Dialog>

  <Dialog v-model:visible="importDialog" modal header="Импорт коллекции" :style="{width:'28rem'}">
    <div class="field" style="display: grid; gap: 7px;"><label>Код коллекции</label><textarea class="p-inputtext" style="width: 100%; resize: none; font-family: monospace; font-size: 12px;" rows="6" v-model="importCode" placeholder="Вставьте код..." autofocus></textarea></div>
    <template #footer><Button label="Отмена" text @click="importDialog=false"/><Button label="Импортировать" icon="pi pi-download" @click="importCollection"/></template>
  </Dialog>

  <Dialog v-model:visible="dialog" modal :header="dialogWeapon?.name ?? ''" class="skin-dialog" :style="{ width: 'min(1080px, 96vw)' }">
    <div class="dialog-toolbar">
      <InputText v-model="dialogSearch" placeholder="Поиск скина..." autofocus />
      <div class="wear-seed">
        <div class="wear-box">
          <span>Wear (float): <b>{{ wear.toFixed(4) }}</b></span>
          <Slider :model-value="wear" @update:model-value="v => wear = Array.isArray(v) ? v[0] : v" :min="picked?.minWear ?? 0" :max="picked?.maxWear ?? 1" :step="0.0001" />
        </div>
        <div class="seed-box"><span>Seed</span><InputNumber v-model="seed" :min="0" :max="1000" showButtons /></div>
      </div>
    </div>
    <div class="skin-grid">
      <button v-for="s in dialogSkins" :key="s.paint" type="button" class="skin-card" :class="{ selected: picked?.paint === s.paint }" :style="{ '--rarity': s.color }" @click="pick(s)">
        <img :src="s.image" :alt="s.name" loading="lazy" />
        <span>{{ s.name.split('| ')[1] ?? s.name }}</span>
      </button>
    </div>
    <template #footer>
      <Button label="Сбросить скин" severity="danger" text :disabled="!dialogWeapon || !mySkins[dialogWeapon.weapon]" :loading="saving" @click="resetSkin" />
      <Button label="Отмена" text @click="dialog = false" />
      <Button label="Сохранить" icon="pi pi-check" :disabled="!picked" :loading="saving" @click="save" />
    </template>
  </Dialog>
</template>

// admin/ui/src/views/SkinchangerView.tsx
import { useEffect, useMemo, useState } from "react";
import {
  DownloadSimple,
  MagnifyingGlass,
  Plus,
  ShareNetwork,
  Trash,
} from "@phosphor-icons/react";
import { SteamIcon as SteamLogo } from "../components/brand-icons";
import { useSearchParams } from "react-router-dom";
import { toast } from "sonner";
import {
  api,
  getMe,
  type Agent,
  type CosmeticLoadout,
  type Glove,
  type Me,
  type Skin,
} from "../api";
import { faceitLevel } from "../faceit";
import {
  Badge,
  Button,
  Dialog,
  Input,
  Select,
  Slider,
  Textarea,
} from "../components/ui";
import { Tabs, TabsList, TabsTrigger } from "../components/ui/tabs";
interface Weapon {
  weapon: string;
  name: string;
  category: string;
  image: string;
  team: "both" | "ct" | "t";
}
interface CatalogSkin {
  name: string;
  weapon: string;
  paint: number;
  color: string;
  image: string;
  minWear: number;
  maxWear: number;
}
interface Known {
  steamId: string;
  name: string;
  lastSeenAt: string;
  avatarUrl?: string | null;
  profileUrl?: string | null;
  faceitElo?: number | null;
  faceitNickname?: string | null;
}
interface Collection {
  id: number;
  name: string;
  active: boolean;
  count: number;
}
interface CatalogGlove {
  id: string;
  name: string;
  definitionIndex: number;
  paintKit: number;
  minWear: number;
  maxWear: number;
  color: string;
  image: string;
}
interface CatalogAgent {
  id: string;
  name: string;
  team: "ct" | "t";
  model: string;
  color: string;
  image: string;
}
const categories = [
  ["all", "Всё"],
  ["sfui_invpanel_filter_melee", "Ножи"],
  ["csgo_inventory_weapon_category_pistols", "Пистолеты"],
  ["csgo_inventory_weapon_category_rifles", "Винтовки"],
  ["csgo_inventory_weapon_category_smgs", "SMG"],
  ["csgo_inventory_weapon_category_heavy", "Тяжёлое"],
  ["loadoutslot_equipment", "Zeus"],
  ["gloves", "Перчатки"],
  ["agents", "Агенты"],
];
export default function SkinchangerView() {
  const [params] = useSearchParams(),
    [me, setMe] = useState<Me | null>(null),
    [players, setPlayers] = useState<Known[]>([]),
    [targetId, setTargetId] = useState(""),
    [weapons, setWeapons] = useState<Weapon[]>([]),
    [skinMap, setSkinMap] = useState(new Map<string, CatalogSkin[]>()),
    [gloves, setGloves] = useState<CatalogGlove[]>([]),
    [agents, setAgents] = useState<CatalogAgent[]>([]),
    [loadout, setLoadout] = useState<CosmeticLoadout>({
      skins: [],
      gloves: [],
      agents: [],
    }),
    [collections, setCollections] = useState<Collection[]>([]),
    [category, setCategory] = useState("all"),
    [search, setSearch] = useState(""),
    [picker, setPicker] = useState<Weapon | null>(null),
    [scope, setScope] = useState<"both" | "ct" | "t">("both"),
    [picked, setPicked] = useState<CatalogSkin | null>(null),
    [wear, setWear] = useState(0.01),
    [seed, setSeed] = useState(0),
    [pickerSearch, setPickerSearch] = useState(""),
    [collectionOpen, setCollectionOpen] = useState(false),
    [collectionName, setCollectionName] = useState(""),
    [importOpen, setImportOpen] = useState(false),
    [importCode, setImportCode] = useState(""),
    [cosmetic, setCosmetic] = useState<{
      kind: "gloves" | "agents";
      team: "ct" | "t";
    } | null>(null),
    [pickedGlove, setPickedGlove] = useState<CatalogGlove | null>(null),
    [pickedAgent, setPickedAgent] = useState<CatalogAgent | null>(null),
    [cosmeticWear, setCosmeticWear] = useState(0.01),
    [cosmeticSeed, setCosmeticSeed] = useState(0);
  const target = players.find((p) => p.steamId === targetId) ?? null,
    self = !me?.isAdmin || !target || target.steamId === me.steamId,
    root = self ? "/api/me" : `/api/players/${target!.steamId}`,
    profile = self
      ? me && {
          ...me,
          profileUrl: `https://steamcommunity.com/profiles/${me.steamId}`,
        }
      : target;
  const skins = useMemo(
      () =>
        Object.fromEntries(
          loadout.skins.map((s) => [`${s.weapon}:${s.team}`, s]),
        ),
      [loadout],
    ),
    myGloves = useMemo(
      () => Object.fromEntries(loadout.gloves.map((g) => [g.team, g])),
      [loadout],
    ),
    myAgents = useMemo(
      () => Object.fromEntries(loadout.agents.map((a) => [a.team, a])),
      [loadout],
    );
  const getSkin = (w: string) => {
      const x = skins[`${w}:both`] ?? skins[`${w}:ct`] ?? skins[`${w}:t`];
      return x
        ? (skinMap.get(w)?.find((s) => s.paint === x.paintKit) ?? null)
        : null;
    },
    getGlove = (t: "ct" | "t") => {
      const x = myGloves[t];
      return x
        ? (gloves.find(
            (g) =>
              g.definitionIndex === x.definitionIndex &&
              g.paintKit === x.paintKit,
          ) ?? null)
        : null;
    },
    getAgent = (t: "ct" | "t") => {
      const x = myAgents[t];
      return x ? (agents.find((a) => a.model === x.model) ?? null) : null;
    };
  const load = async (path = root) =>
      setLoadout(await api<CosmeticLoadout>(`${path}/cosmetics`)),
    loadCollections = async () => {
      if (self) setCollections(await api<Collection[]>("/api/me/collections"));
    };
  useEffect(() => {
    let active = true;
    void (async () => {
      const identity = await getMe();
      if (!active) return;
      setMe(identity);
      const [cat, cos] = await Promise.all([
        fetch("/skins-catalog.json").then((r) => r.json()),
        fetch("/cosmetics-catalog.json").then((r) => r.json()),
      ]);
      if (!active) return;
      setWeapons(cat.weapons);
      const grouped = new Map<string, CatalogSkin[]>();
      for (const s of cat.skins) {
        const a = grouped.get(s.weapon) ?? [];
        a.push(s);
        grouped.set(s.weapon, a);
      }
      setSkinMap(grouped);
      setGloves(cos.gloves);
      setAgents(cos.agents);
      let path = "/api/me";
      if (identity?.isAdmin) {
        const ps = await api<Known[]>("/api/players/known");
        if (!active) return;
        setPlayers(ps);
        const id = params.get("steamId") ?? identity.steamId;
        setTargetId(id);
        if (id !== identity.steamId) path = `/api/players/${id}`;
      }
      const [nextLoadout, cols] = await Promise.all([
        api<CosmeticLoadout>(`${path}/cosmetics`),
        api<Collection[]>("/api/me/collections"),
      ]);
      if (!active) return;
      setLoadout(nextLoadout);
      if (!cols.length) {
        await api("/api/me/collections", {
          method: "POST",
          body: JSON.stringify({ name: "По умолчанию" }),
        });
        if (active)
          setCollections(await api<Collection[]>("/api/me/collections"));
      } else setCollections(cols);
    })();
    return () => {
      active = false;
    };
  }, []);
  async function retarget(id: string) {
    setTargetId(id);
    const isSelf = id === me?.steamId;
    setLoadout(
      await api<CosmeticLoadout>(
        `${isSelf ? "/api/me" : `/api/players/${id}`}/cosmetics`,
      ),
    );
  }
  const visible = weapons.filter(
    (w) =>
      (category === "all" || w.category === category) &&
      (!search ||
        w.name.toLowerCase().includes(search.toLowerCase()) ||
        (getSkin(w.weapon)?.name ?? "")
          .toLowerCase()
          .includes(search.toLowerCase())),
  );
  function openWeapon(w: Weapon) {
    const s = w.team === "both" ? "both" : w.team,
      set = skins[`${w.weapon}:${s}`];
    setPicker(w);
    setScope(s);
    setPicked(
      set
        ? (skinMap.get(w.weapon)?.find((x) => x.paint === set.paintKit) ?? null)
        : null,
    );
    setWear(set?.wear ?? 0.01);
    setSeed(set?.seed ?? 0);
    setPickerSearch("");
  }
  function changeScope(s: string) {
    const team = s as "both" | "ct" | "t";
    setScope(team);
    if (!picker) return;
    const set = skins[`${picker.weapon}:${team}`];
    setPicked(
      set
        ? (skinMap.get(picker.weapon)?.find((x) => x.paint === set.paintKit) ??
            null)
        : null,
    );
    setWear(set?.wear ?? 0.01);
    setSeed(set?.seed ?? 0);
  }
  async function saveSkin() {
    if (!picker || !picked) return;
    await api(`${root}/skins/${picker.weapon}`, {
      method: "PUT",
      body: JSON.stringify({
        weapon: picker.weapon,
        team: scope,
        paintKit: picked.paint,
        wear,
        seed,
      }),
    });
    await load();
    setPicker(null);
    toast.success("Скин сохранён");
  }
  async function resetSkin() {
    if (!picker) return;
    await api(`${root}/skins/${picker.weapon}/${scope}`, { method: "DELETE" });
    await load();
    setPicker(null);
    toast.success("Скин сброшен");
  }
  async function createCollection() {
    if (!collectionName.trim()) return;
    await api("/api/me/collections", {
      method: "POST",
      body: JSON.stringify({ name: collectionName.trim() }),
    });
    setCollectionName("");
    setCollectionOpen(false);
    await loadCollections();
  }
  async function activate(c: Collection) {
    if (c.active) return;
    await api(`/api/me/collections/${c.id}/activate`, { method: "POST" });
    await Promise.all([loadCollections(), load()]);
  }
  async function remove(c: Collection) {
    if (!confirm(`Удалить коллекцию «${c.name}»?`)) return;
    await api(`/api/me/collections/${c.id}`, { method: "DELETE" });
    await Promise.all([loadCollections(), load()]);
  }
  async function share(c: Collection) {
    const list = await api<Skin[]>(`/api/me/collections/${c.id}/skins`);
    const code = btoa(
      unescape(
        encodeURIComponent(JSON.stringify({ name: c.name, skins: list })),
      ),
    );
    await navigator.clipboard.writeText(code);
    toast.success("Код коллекции скопирован");
  }
  async function importCollection() {
    try {
      const data = JSON.parse(
        decodeURIComponent(escape(atob(importCode.trim()))),
      );
      await api("/api/me/collections", {
        method: "POST",
        body: JSON.stringify(data),
      });
      setImportOpen(false);
      setImportCode("");
      await loadCollections();
      toast.success("Коллекция импортирована");
    } catch {
      toast.error("Неверный код коллекции");
    }
  }
  function openCosmetic(kind: "gloves" | "agents", team: "ct" | "t") {
    setCosmetic({ kind, team });
    const g = myGloves[team],
      a = myAgents[team];
    setPickedGlove(
      g
        ? (gloves.find(
            (x) =>
              x.definitionIndex === g.definitionIndex &&
              x.paintKit === g.paintKit,
          ) ?? null)
        : null,
    );
    setPickedAgent(
      a ? (agents.find((x) => x.model === a.model) ?? null) : null,
    );
    setCosmeticWear(g?.wear ?? 0.01);
    setCosmeticSeed(g?.seed ?? 0);
  }
  async function saveCosmetic() {
    if (!cosmetic) return;
    if (cosmetic.kind === "gloves" && pickedGlove)
      await api(`${root}/gloves/${cosmetic.team}`, {
        method: "PUT",
        body: JSON.stringify({
          team: cosmetic.team,
          definitionIndex: pickedGlove.definitionIndex,
          paintKit: pickedGlove.paintKit,
          wear: cosmeticWear,
          seed: cosmeticSeed,
        }),
      });
    if (cosmetic.kind === "agents" && pickedAgent)
      await api(`${root}/agents/${cosmetic.team}`, {
        method: "PUT",
        body: JSON.stringify({ team: cosmetic.team, model: pickedAgent.model }),
      });
    await load();
    setCosmetic(null);
    toast.success("Loadout сохранён");
  }
  async function resetCosmetic() {
    if (!cosmetic) return;
    await api(`${root}/${cosmetic.kind}/${cosmetic.team}`, {
      method: "DELETE",
    });
    await load();
    setCosmetic(null);
    toast.success("Слот сброшен");
  }
  return (
    <>
      <header className="page-header">
        <div>
          <p className="kicker">LOADOUT LAB</p>
          <h1>Skinchanger</h1>
        </div>
        {me?.isAdmin && (
          <Select value={targetId} onChange={(e) => retarget(e.target.value)}>
            {players.map((p) => (
              <option value={p.steamId} key={p.steamId}>
                {p.name} · {p.steamId}
              </option>
            ))}
          </Select>
        )}
      </header>
      {profile && (
        <section className="profile-bar">
          {profile.avatarUrl ? (
            <img src={profile.avatarUrl} />
          ) : (
            <span className="avatar-fallback">{profile.name[0]}</span>
          )}
          <div>
            <h2>{profile.name}</h2>
            <small>{profile.steamId}</small>
          </div>
          <a
            href={
              profile.profileUrl ??
              `https://steamcommunity.com/profiles/${profile.steamId}`
            }
            target="_blank"
          >
            <SteamLogo /> Steam
          </a>
          {profile.faceitElo && (
            <Badge tone="warning">
              <img src={`/faceit/lvl${faceitLevel(profile.faceitElo)}.svg`} />
              {profile.faceitElo} ELO
            </Badge>
          )}
        </section>
      )}
      <div className="loadout-layout">
        {self && (
          <aside className="collections">
            <div className="aside-head">
              <span>КОЛЛЕКЦИИ</span>
              <b>{collections.length}</b>
            </div>
            {collections.map((c) => (
              <div
                className={`collection ${c.active ? "active" : ""}`}
                key={c.id}
                onClick={() => activate(c)}
              >
                <div>
                  <b>{c.name}</b>
                  <small>{c.count} скинов</small>
                </div>
                <div className="collection-actions">
                  <Button
                    variant="ghost"
                    size="icon-xs"
                    aria-label={`Поделиться коллекцией ${c.name}`}
                    onClick={(e) => {
                      e.stopPropagation();
                      void share(c);
                    }}
                  >
                    <ShareNetwork />
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon-xs"
                    aria-label={`Удалить коллекцию ${c.name}`}
                    onClick={(e) => {
                      e.stopPropagation();
                      void remove(c);
                    }}
                  >
                    <Trash />
                  </Button>
                </div>
              </div>
            ))}
            <div className="aside-buttons">
              <Button
                variant="secondary"
                onClick={() => setCollectionOpen(true)}
              >
                <Plus /> Создать
              </Button>
              <Button variant="ghost" onClick={() => setImportOpen(true)}>
                <DownloadSimple /> Импорт
              </Button>
            </div>
          </aside>
        )}
        <section className="loadout-main">
          <div className="skin-toolbar">
            <Tabs value={category} onValueChange={setCategory}>
              <TabsList className="h-auto flex-wrap justify-start">
                {categories.map(([id, label]) => (
                  <TabsTrigger key={id} value={id}>
                    {label}
                  </TabsTrigger>
                ))}
              </TabsList>
            </Tabs>
            <label className="search">
              <MagnifyingGlass />
              <Input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Поиск"
              />
            </label>
          </div>
          {category === "gloves" || category === "agents" ? (
            <div className="weapon-grid">
              {(["ct", "t"] as const).map((team) => {
                const item =
                  category === "gloves" ? getGlove(team) : getAgent(team);
                return (
                  <button
                    className="weapon-card"
                    style={
                      {
                        "--rarity": item?.color ?? "#30343d",
                      } as React.CSSProperties
                    }
                    onClick={() => openCosmetic(category, team)}
                    key={team}
                  >
                    {item && <img src={item.image} />}
                    <b>{team === "ct" ? "COUNTER-TERRORIST" : "TERRORIST"}</b>
                    <span>
                      {item?.name ??
                        `Выбрать ${category === "gloves" ? "перчатки" : "агента"}`}
                    </span>
                  </button>
                );
              })}
            </div>
          ) : (
            <div className="weapon-grid">
              {visible.map((w) => {
                const skin = getSkin(w.weapon);
                return (
                  <button
                    className="weapon-card"
                    style={
                      {
                        "--rarity": skin?.color ?? "#30343d",
                      } as React.CSSProperties
                    }
                    onClick={() => openWeapon(w)}
                    key={w.weapon}
                  >
                    <img
                      className={!skin ? "vanilla" : ""}
                      src={skin?.image ?? w.image}
                    />
                    <b>{w.name}</b>
                    <span>{skin?.name.split("| ")[1] ?? "Добавить скин"}</span>
                    <em>{w.team.toUpperCase()}</em>
                  </button>
                );
              })}
            </div>
          )}
        </section>
      </div>
      <Dialog
        open={collectionOpen}
        onOpenChange={setCollectionOpen}
        title="Новая коллекция"
        footer={
          <>
            <Button variant="ghost" onClick={() => setCollectionOpen(false)}>
              Отмена
            </Button>
            <Button onClick={createCollection}>Создать</Button>
          </>
        }
      >
        <label className="field">
          Название
          <Input
            value={collectionName}
            onChange={(e) => setCollectionName(e.target.value)}
            autoFocus
          />
        </label>
      </Dialog>
      <Dialog
        open={importOpen}
        onOpenChange={setImportOpen}
        title="Импорт коллекции"
        footer={<Button onClick={importCollection}>Импортировать</Button>}
      >
        <Textarea
          value={importCode}
          onChange={(e) => setImportCode(e.target.value)}
          rows={7}
          placeholder="Вставьте код коллекции"
        />
      </Dialog>
      <Dialog
        open={!!picker}
        onOpenChange={(v) => !v && setPicker(null)}
        title={picker?.name ?? ""}
        wide
        footer={
          <>
            <Button variant="danger" onClick={resetSkin}>
              Сбросить
            </Button>
            <Button variant="ghost" onClick={() => setPicker(null)}>
              Отмена
            </Button>
            <Button disabled={!picked} onClick={saveSkin}>
              Сохранить
            </Button>
          </>
        }
      >
        <div className="picker-toolbar">
          {picker && (
            <Tabs value={scope} onValueChange={changeScope}>
              <TabsList>
                {(picker.team === "both"
                  ? ["both", "t", "ct"]
                  : ([picker.team] as const)
                ).map((t) => (
                  <TabsTrigger value={t} key={t}>
                    {t.toUpperCase()}
                  </TabsTrigger>
                ))}
              </TabsList>
            </Tabs>
          )}
          <Input
            value={pickerSearch}
            onChange={(e) => setPickerSearch(e.target.value)}
            placeholder="Поиск скина"
          />
          <label>
            Wear <b>{wear.toFixed(4)}</b>
            <Slider
              value={[wear]}
              onValueChange={(v) => setWear(v[0])}
              min={picked?.minWear ?? 0}
              max={picked?.maxWear ?? 1}
              step={0.0001}
            />
          </label>
          <label>
            Seed
            <Input
              type="number"
              min={0}
              max={1000}
              value={seed}
              onChange={(e) => setSeed(+e.target.value)}
            />
          </label>
        </div>
        <div className="skin-grid">
          {(picker ? (skinMap.get(picker.weapon) ?? []) : [])
            .filter((s) =>
              s.name.toLowerCase().includes(pickerSearch.toLowerCase()),
            )
            .map((s) => (
              <button
                className={`skin-card ${picked?.paint === s.paint ? "selected" : ""}`}
                style={{ "--rarity": s.color } as React.CSSProperties}
                onClick={() => {
                  setPicked(s);
                  setWear(Math.min(Math.max(wear, s.minWear), s.maxWear));
                }}
                key={s.paint}
              >
                <img src={s.image} />
                <span>{s.name.split("| ")[1] ?? s.name}</span>
              </button>
            ))}
        </div>
      </Dialog>
      <Dialog
        open={!!cosmetic}
        onOpenChange={(v) => !v && setCosmetic(null)}
        title={`${cosmetic?.kind === "gloves" ? "Перчатки" : "Агент"} · ${cosmetic?.team.toUpperCase()}`}
        wide
        footer={
          <>
            <Button variant="danger" onClick={resetCosmetic}>
              Сбросить
            </Button>
            <Button variant="ghost" onClick={() => setCosmetic(null)}>
              Отмена
            </Button>
            <Button
              disabled={
                cosmetic?.kind === "gloves" ? !pickedGlove : !pickedAgent
              }
              onClick={saveCosmetic}
            >
              Сохранить
            </Button>
          </>
        }
      >
        {cosmetic?.kind === "gloves" && (
          <div className="picker-toolbar cosmetic-controls">
            <label>
              Wear <b>{cosmeticWear.toFixed(4)}</b>
              <Slider
                value={[cosmeticWear]}
                onValueChange={(v) => setCosmeticWear(v[0])}
                min={pickedGlove?.minWear ?? 0}
                max={pickedGlove?.maxWear ?? 1}
                step={0.0001}
              />
            </label>
            <label>
              Seed
              <Input
                type="number"
                min={0}
                max={1000}
                value={cosmeticSeed}
                onChange={(e) => setCosmeticSeed(+e.target.value)}
              />
            </label>
          </div>
        )}
        <div className="skin-grid">
          {cosmetic?.kind === "gloves"
            ? gloves.map((g) => (
                <button
                  className={`skin-card ${pickedGlove?.id === g.id ? "selected" : ""}`}
                  style={{ "--rarity": g.color } as React.CSSProperties}
                  onClick={() => {
                    setPickedGlove(g);
                    setCosmeticWear(
                      Math.min(Math.max(cosmeticWear, g.minWear), g.maxWear),
                    );
                  }}
                  key={g.id}
                >
                  <img src={g.image} />
                  <span>{g.name}</span>
                </button>
              ))
            : agents
                .filter((a) => a.team === cosmetic?.team)
                .map((a) => (
                  <button
                    className={`skin-card agent ${pickedAgent?.id === a.id ? "selected" : ""}`}
                    style={{ "--rarity": a.color } as React.CSSProperties}
                    onClick={() => setPickedAgent(a)}
                    key={a.id}
                  >
                    <img src={a.image} />
                    <span>{a.name}</span>
                  </button>
                ))}
        </div>
      </Dialog>
    </>
  );
}
